// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs remove-from-zip`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "zip-viewer",
    "icon": "👁️",
    "name": {
      "en": "ZIP Viewer",
      "ja": "ZIPの中身を確認",
      "zh": "查看 ZIP",
      "de": "ZIP-Viewer",
      "es": "Visor de ZIP"
    },
    "desc": {
      "en": "See what's inside a .zip without extracting it.",
      "ja": "展開せずに.zipの中身を確認します。",
      "zh": "不解压也能看 .zip 里面有什么。",
      "de": "Schau in ein .zip hinein, ohne es zu entpacken.",
      "es": "Ve qué contiene un .zip sin extraerlo."
    }
  },
  {
    "slug": "create-zip",
    "icon": "🗜️",
    "name": {
      "en": "Create ZIP",
      "ja": "ZIPを作成",
      "zh": "打包 ZIP",
      "de": "ZIP erstellen",
      "es": "Crear ZIP"
    },
    "desc": {
      "en": "Bundle your files into a single .zip archive.",
      "ja": "複数のファイルを1つの.zipにまとめます。",
      "zh": "把多个文件打包成一个 .zip 压缩包。",
      "de": "Deine Dateien zu einem einzigen .zip-Archiv bündeln.",
      "es": "Reúne tus archivos en un solo archivo .zip."
    }
  },
  {
    "slug": "merge-zip",
    "icon": "🔗",
    "name": {
      "en": "Merge ZIP",
      "ja": "Zip結合",
      "zh": "合并 ZIP",
      "de": "ZIP zusammenführen",
      "es": "Combinar ZIP"
    },
    "desc": {
      "en": "Combine multiple .zip files into one.",
      "ja": "複数の .zip を1つに結合。",
      "zh": "把多个 .zip 合并为一个。",
      "de": "Mehrere .zip-Dateien zu einer zusammenführen.",
      "es": "Combina varios .zip en uno."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'remove-from-zip';
